### ISSUE TITLE
sord_validate and lv2lint fail on bshapr

### ISSUE THREAD

**Issue by dvzrv** [sjaehn/BShapr#7] opened 2019-11-21 21:32 UTC
While building 0.4 for Arch Linux I ran `sord_validate` ([man_page](https://jlk.fjfi.cvut.cz/arch/manpages/man/sord_validate.1)) and `lv2lint` ([man page](https://jlk.fjfi.cvut.cz/arch/manpages/man/lv2lint.1)) on bshapr after build.

Bot tools fail on it though: 
[bshapr-0.4-1-x86_64-check.log](https://github.com/sjaehn/BShapr/files/3876856/bshapr-0.4-1-x86_64-check.log)

**Comment by sjaehn** [comment] 2019-11-22 09:30
Thank you for your feedback. Please notice that I just subitted a commit ( 60c0934d36cffc6395bab7e152b7769adf59c70e ) containing two important bugfixes. But this shouln't effect the output of `sord_validate` and `lv2lint`, respectively.

About the `lv2lint` output. I can reproduce:
`[WARN]  Linking` - c++ libraries... 
`[WARN]  Author Email` - wontfix, sorry
`[FAIL]  Version Minor` - The plugin is still in early stages of development. Features will be added or removed. I always try to make it backward compatible. But I can't guarantee 100 % backward compatibility, yet.  But `version minor` and `version micro` will follow.
`[FAIL]  Version Micror` - vide supra

In addition, I can't reproduce:
`[WARN]  Class` - It looks like you used an older lv2 version. B.Shapr is defined as `a lv2:Plugin, lv2:EnvelopePlugin`. EnvelopePlugin was added in version 14.0 or 16.0, I think. Older versions may only interpret `lv2:Plugin`.
`[FAIL]  Toolkit` - Wondering. X11UI is in the lv2 specifications since 2011 ?!

**Closed as completed** 2019-12-22 22:02 UTC
